actions:
  JointPositionAction:
    clip: null
    joint_ids: null
    joint_names:
    - .*
    offset:
    - -0.1
    - -0.1
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.3
    - 0.3
    - 0.3
    - 0.3
    - -0.2
    - -0.2
    - 0.25
    - -0.25
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.97
    - 0.97
    - 0.15
    - -0.15
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    scale:
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
commands:
  base_velocity:
    ranges:
      ang_vel_z:
      - -0.25
      - 0.25
      heading: null
      lin_vel_x:
      - 0.15
      - 0.8
      lin_vel_y:
      - -0.15
      - 0.15
damping:
- 2.0
- 2.0
- 2.0
- 4.0
- 2.0
- 2.0
- 2.0
- 2.0
- 2.0
- 4.0
- 2.0
- 2.0
- 5.0
- 5.0
- 5.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
default_joint_pos:
- -0.1
- -0.1
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.3
- 0.3
- 0.3
- 0.3
- -0.2
- -0.2
- 0.25
- -0.25
- 0.0
- 0.0
- 0.0
- 0.0
- 0.97
- 0.97
- 0.15
- -0.15
- 0.0
- 0.0
- 0.0
- 0.0
joint_ids_map:
- 0
- 6
- 12
- 1
- 7
- 13
- 2
- 8
- 14
- 3
- 9
- 15
- 22
- 4
- 10
- 16
- 23
- 5
- 11
- 17
- 24
- 18
- 25
- 19
- 26
- 20
- 27
- 21
- 28
observations:
  base_ang_vel:
    clip: null
    history_length: 5
    params: {}
    scale:
    - 0.2
    - 0.2
    - 0.2
  projected_gravity:
    clip: null
    history_length: 5
    params: {}
    scale:
    - 1.0
    - 1.0
    - 1.0
  velocity_commands:
    clip: null
    history_length: 5
    params:
      command_name: base_velocity
    scale:
    - 1.0
    - 1.0
    - 1.0
  joint_pos_rel:
    clip: null
    history_length: 5
    params: {}
    scale:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  joint_vel_rel:
    clip: null
    history_length: 5
    params: {}
    scale:
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
  last_action:
    clip: null
    history_length: 5
    params: {}
    scale:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  obstacle_scan:
    params:
      num_rays: 9
      max_distance: 6.0
      fov_deg: 180.0
    clip:
    - 0.0
    - 6.0
    scale:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    history_length: 5
step_dt: 0.02
stiffness:
- 100.0
- 100.0
- 100.0
- 150.0
- 40.0
- 40.0
- 100.0
- 100.0
- 100.0
- 150.0
- 40.0
- 40.0
- 200.0
- 200.0
- 200.0
- 40.0
- 40.0
- 40.0
- 40.0
- 40.0
- 40.0
- 40.0
- 40.0
- 40.0
- 40.0
- 40.0
- 40.0
- 40.0
- 40.0
